# Model Screening Test Configuration (1 Model Only)
# 수정사항 검증용

general:
  data_path: "../data/"
  result_path: "./screening_results/"
  max_disk_usage_gb: 80

# 테스트 모델: Llama-3.2-Korean-3B (이전 최고 성능 모델)
models:
  - model_name: "Bllossom/llama-3.2-Korean-Bllossom-3B"
    nickname: "Llama-3.2-Korean-3B"
    description: "Llama 3.2 Korean Bllossom 3B (Fixed)"

# Tokenizer 설정
tokenizer:
  encoder_max_len: 512
  decoder_max_len: 100
  # BOS/EOS 토큰은 토크나이저에서 자동으로 읽어옴 (하드코딩 제거)
  special_tokens:
    - "#Person1#"
    - "#Person2#"
    - "#Person3#"
    - "#PhoneNumber#"
    - "#Address#"
    - "#PassportNumber#"

# QLoRA 설정 (4bit 양자화)
qlora:
  load_in_4bit: true
  bnb_4bit_compute_dtype: "bfloat16"
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_use_double_quant: true

# 추론 설정
inference:
  batch_size: 16
  no_repeat_ngram_size: 2
  early_stopping: true
  generate_max_length: 100
  num_beams: 4
  remove_tokens:
    - "<usr>"
    - "</s>"
    - "<pad>"
    - "<unk>"

# W&B 설정
wandb:
  enabled: true
  project: "dialogue-summarization-screening"
  entity: null
  name_prefix: "screening-fixed-test"
  tags:
    - "model-screening"
    - "fixed-version"
    - "test-run"
    - "qlora-4bit"

# 디스크 관리
disk_management:
  check_before_download: true
  check_after_inference: true
  auto_cleanup_cache: true
  cleanup_checkpoints: true
  keep_results_only: true
